/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Repair.*;
import java.awt.Color;
import static javafx.scene.paint.Color.color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import javax.swing.JFrame;

/**
 *
 * @author Gurkan
 */
public class StatisticOfRepair extends javax.swing.JFrame {

    /**
     * Creates new form StatisticOfRepair
     */
    
    
    public StatisticOfRepair() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Type Of Car Model");
        jButton1.setPreferredSize(new java.awt.Dimension(199, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Consume Diesel Tools");
        jButton2.setPreferredSize(new java.awt.Dimension(179, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Male-Female Statistics");
        jButton3.setPreferredSize(new java.awt.Dimension(179, 25));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 102, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Consume Gas Tools");
        jButton4.setPreferredSize(new java.awt.Dimension(179, 25));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 102, 102));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Consume Electric Tools");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Admin Pictures/Grafick.gif"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Admin Pictures/Grafick.gif"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Admin Pictures/Grafick.gif"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Admin Pictures/Grafick.gif"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Admin Pictures/Grafick.gif"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Admin Pictures/istatistik.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(71, 71, 71)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton5)
                .addGap(26, 26, 26)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(852, 852, 852)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(880, 880, 880)
                .addComponent(jLabel3))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel3))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1048, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultPieDataset pieDataset=new DefaultPieDataset();
        pieDataset.setValue("Diesel Car = "+DieselCar.getCountDiesel(), DieselCar.getCountDiesel() );
        pieDataset.setValue("Electric Car = "+ElectricCar.getCountElectric(), ElectricCar.getCountElectric());
        pieDataset.setValue("Gasoline Car = "+GasolineCar.getCountGasoline(), GasolineCar.getCountGasoline());
        
        
        JFreeChart chart=ChartFactory.createPieChart3D("CARS", pieDataset, true, true, true);
        PiePlot3D p=(PiePlot3D)chart.getPlot();
        //p.setForegroundAlpha(TOP_ALIGNMENT);
        ChartFrame frame=new ChartFrame("Countt",chart);
        frame.setVisible(true);
        frame.setSize(650,700);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultCategoryDataset dataset=new DefaultCategoryDataset();
        dataset.setValue(DieselCar.getCountFemale(), "Female-Male", "Diesel Female");
        dataset.setValue(DieselCar.getCountMale(), "Female-Male", "Diesel Male");
        dataset.setValue(GasolineCar.getCountFemale(), "Female-Male", "Gas. Female");
        dataset.setValue(GasolineCar.getCountMale(), "Female-Male", "Gas. Male");
        dataset.setValue(ElectricCar.getCountFemale(), "Female-Male", "Electric Female");
        dataset.setValue(ElectricCar.getCountMale(), "Female-Male", "Electric Male");
        dataset.setValue(Repair.getCountFemale(), "Female-Male", "Total Female");
        dataset.setValue(Repair.getCountMale(), "Female-Male", "Total Male");
        JFreeChart chart=ChartFactory.createBarChart3D("Gender Statistics", "Female-Male", "COUNT", dataset, PlotOrientation.VERTICAL, false , true, false);
        CategoryPlot p=chart.getCategoryPlot();
        chart.setBackgroundPaint(Color.CYAN);        
        chart.setBorderPaint(Color.RED);
        chart.getTitle().setBackgroundPaint(Color.white);
        p.setRangeGridlinePaint(Color.blue);
        ChartFrame frame=new ChartFrame("Bar Chart ve Sakatlar",chart);
        frame.setVisible(true);
        frame.setSize(1100,779);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultCategoryDataset dataset=new DefaultCategoryDataset();
        dataset.setValue(DieselCar.getSpentDFuel(), "Female-Male", "Fuel");
        dataset.setValue(DieselCar.getSpentDGearBox(), "Female-Male", "GearBox");
        dataset.setValue(DieselCar.getSpentDRadiator(), "Female-Male", "Radiator");
        dataset.setValue(DieselCar.getSpentDbattery(), "Female-Male", "Battery");
        dataset.setValue(DieselCar.getSpentDengine(), "Female-Male", "Engine");
        dataset.setValue(DieselCar.getSpentSeat(), "Female-Male", "Seat");
        dataset.setValue(DieselCar.getSpentTire(), "Female-Male", "Tire");
        dataset.setValue(DieselCar.getSpentheadlight(), "Female-Male", "HeadLight");
        dataset.setValue(DieselCar.getSpentrim(), "Female-Male", "Rim");
        dataset.setValue(DieselCar.getSpentwindow(), "Female-Male", "Window");
        
        
        JFreeChart chart=ChartFactory.createBarChart3D("Statistics of Spent TooLs", "Tools", "COUNT", dataset, PlotOrientation.VERTICAL, false , true, false);
        CategoryPlot p=chart.getCategoryPlot();
        chart.setBackgroundPaint(Color.CYAN);        
        chart.setBorderPaint(Color.RED);
        chart.getTitle().setBackgroundPaint(Color.white);
        p.setRangeGridlinePaint(Color.blue);
        ChartFrame frame=new ChartFrame("Bar Chart ve Sakatlar",chart);
        frame.setVisible(true);
        frame.setSize(1000,779);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DefaultCategoryDataset dataset=new DefaultCategoryDataset();
        dataset.setValue(GasolineCar.getSpentGFuel(), "Female-Male", "Fuel");
        dataset.setValue(GasolineCar.getSpentGGearBox(), "Female-Male", "GearBox");
        dataset.setValue(GasolineCar.getSpentGRadiator(), "Female-Male", "Radiator");
        dataset.setValue(GasolineCar.getSpentGbattery(), "Female-Male", "Battery");
        dataset.setValue(GasolineCar.getSpentGengine(), "Female-Male", "Engine");
        dataset.setValue(GasolineCar.getSpentSeat(), "Female-Male", "Seat");
        dataset.setValue(GasolineCar.getSpentTire(), "Female-Male", "Tire");
        dataset.setValue(GasolineCar.getSpentheadlight(), "Female-Male", "HeadLight");
        dataset.setValue(GasolineCar.getSpentrim(), "Female-Male", "Rim");
        dataset.setValue(GasolineCar.getSpentwindow(), "Female-Male", "Window");
        
        
        JFreeChart chart=ChartFactory.createBarChart3D("Statistics of Spent TooLs", "Tools", "COUNT", dataset, PlotOrientation.VERTICAL, false , true, false);
        CategoryPlot p=chart.getCategoryPlot();
        chart.setBackgroundPaint(Color.CYAN);        
        chart.setBorderPaint(Color.RED);
        chart.getTitle().setBackgroundPaint(Color.white);
        p.setRangeGridlinePaint(Color.blue);
        ChartFrame frame=new ChartFrame("Bar Chart ve Sakatlar",chart);
        frame.setVisible(true);
        frame.setSize(1000,779);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         DefaultCategoryDataset dataset=new DefaultCategoryDataset();
        dataset.setValue(ElectricCar.getSpentEChargeBattery(), "Female-Male", "C. Battery");
        dataset.setValue(ElectricCar.getSpentEGearBox(), "Female-Male", "GearBox");
        dataset.setValue(ElectricCar.getSpentERadiator(), "Female-Male", "Radiator");
        dataset.setValue(ElectricCar.getSpentEbattery(), "Female-Male", "Battery");
        dataset.setValue(ElectricCar.getSpentEengine(), "Female-Male", "Engine");
        dataset.setValue(ElectricCar.getSpentSeat(), "Female-Male", "Seat");
        dataset.setValue(ElectricCar.getSpentTire(), "Female-Male", "Tire");
        dataset.setValue(ElectricCar.getSpentheadlight(), "Female-Male", "HeadLight");
        dataset.setValue(ElectricCar.getSpentrim(), "Female-Male", "Rim");
        dataset.setValue(ElectricCar.getSpentwindow(), "Female-Male", "Window");
        
        
        JFreeChart chart=ChartFactory.createBarChart3D("Statistics of Spent TooLs", "Tools", "COUNT", dataset, PlotOrientation.VERTICAL, false , true, false);
        CategoryPlot p=chart.getCategoryPlot();
        chart.setBackgroundPaint(Color.CYAN);        
        chart.setBorderPaint(Color.RED);
        chart.getTitle().setBackgroundPaint(Color.white);
        p.setRangeGridlinePaint(Color.blue);
        ChartFrame frame=new ChartFrame("Bar Chart ve Sakatlar",chart);
        frame.setVisible(true);
        frame.setSize(1000,779);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatisticOfRepair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatisticOfRepair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatisticOfRepair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatisticOfRepair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatisticOfRepair().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
